spring:
 cloud:
   gateway:
     routes:
       - id: employee-app
         uri: lb://EMPLOYEE-APP
         predicates:
           - Path=/employee/**
         filters:
           - AuthenticationFilter

 application:
   name: TEK-IT-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
